var local_database = [
  {
    imagesrc: "/images/8.jpg",
    name: "电脑",
    lackofitems: "cpu、硬盘、电源",
    price: "99",
    starttime:"2017-04-13",
    endtime:"2018-11-14",
    numbers:"9",
    recoverynumber:"11110",
    recoveryvariety:"设备",
    recoverymode:"上门回收",
    img1: "/images/1.jpg",
    img2: "/images/8.jpg",
    img3: "/images/9.jpg",
    postId:0,
    recoverystate: 0
  },
  {
    imagesrc: "/images/1.jpg",
    name: "电视",
    lackofitems: "电源",
    price: "199",
    starttime: "2018-04-13",
    endtime: "2018-11-14",
    numbers: "1",
    recoverynumber: "11111",
    recoveryvariety: "设备",
    recoverymode: "上门回收",
    img1: "/images/1.jpg",
    img2: "/images/8.jpg",
    img3: "/images/9.jpg",
    postId: 1,
    recoverystate: 0
  },
  {
    imagesrc: "/images/9.jpg",
    name: "收音机",
    lackofitems: "硬盘、电源",
    price: "20",
    starttime: "2018-04-13",
    endtime: "2019-11-14",
    numbers: "44",
    recoverynumber: "11113",
    recoveryvariety: "设备",
    recoverymode: "上门回收",
    img1: "/images/1.jpg",
    img2: "/images/8.jpg",
    img3: "/images/9.jpg",
    postId: 2,
    recoverystate: 0
  },
  {
    imagesrc: "/images/9.jpg",
    name: "电脑",
    lackofitems: "cpu、硬盘、电源",
    price: "99",
    starttime: "2017-04-13",
    endtime: "2018-11-14",
    numbers: "9",
    recoverynumber: "11110",
    recoveryvariety: "设备",
    recoverymode: "上门回收",
    img1: "/images/1.jpg",
    img2: "/images/8.jpg",
    img3: "/images/9.jpg",
    postId: 3,
    recoverystate: 1
  },
  {
    imagesrc: "/images/8.jpg",
    name: "电脑",
    lackofitems: "cpu、硬盘、电源",
    price: "99",
    starttime: "2017-04-13",
    endtime: "2018-11-14",
    numbers: "9",
    recoverynumber: "11110",
    recoveryvariety: "设备",
    recoverymode: "上门回收",
    img1: "/images/1.jpg",
    img2: "/images/8.jpg",
    img3: "/images/9.jpg",
    postId: 4,
    recoverystate: 1
  },
  {
    imagesrc: "/images/8.jpg",
    name: "电脑",
    lackofitems: "cpu、硬盘、电源",
    price: "99",
    starttime: "2017-04-13",
    endtime: "2018-11-14",
    numbers: "9",
    recoverynumber: "11110",
    recoveryvariety: "设备",
    recoverymode: "上门回收",
    img1: "/images/1.jpg",
    img2: "/images/8.jpg",
    img3: "/images/9.jpg",
    postId: 5,
    recoverystate: 0
  },
  {
    imagesrc: "/images/8.jpg",
    name: "电脑",
    lackofitems: "cpu、硬盘、电源",
    price: "99",
    starttime: "2017-04-13",
    endtime: "2018-11-14",
    numbers: "9",
    recoverynumber: "11110",
    recoveryvariety: "设备",
    recoverymode: "上门回收",
    img1: "/images/1.jpg",
    img2: "/images/8.jpg",
    img3: "/images/9.jpg",
    postId: 6,
    recoverystate: 0
  },
  {
    imagesrc: "/images/8.jpg",
    name: "电脑",
    lackofitems: "cpu、硬盘、电源",
    price: "99",
    starttime: "2017-04-13",
    endtime: "2018-11-14",
    numbers: "9",
    recoverynumber: "11110",
    recoveryvariety: "设备",
    recoverymode: "上门回收",
    img1: "/images/1.jpg",
    img2: "/images/8.jpg",
    img3: "/images/9.jpg",
    postId: 7,
    recoverystate: 0
  },
  {
    imagesrc: "/images/8.jpg",
    name: "电脑",
    lackofitems: "cpu、硬盘、电源",
    price: "99",
    starttime: "2017-04-13",
    endtime: "2018-11-14",
    numbers: "9",
    recoverynumber: "11110",
    recoveryvariety: "设备",
    recoverymode: "上门回收",
    img1: "/images/1.jpg",
    img2: "/images/8.jpg",
    img3: "/images/9.jpg",
    postId: 8,
    recoverystate: 0
  },
  {
    imagesrc: "/images/8.jpg",
    name: "电脑",
    lackofitems: "cpu、硬盘、电源",
    price: "99",
    starttime: "2017-04-13",
    endtime: "2018-11-14",
    numbers: "9",
    recoverynumber: "11110",
    recoveryvariety: "设备",
    recoverymode: "上门回收",
    img1: "/images/1.jpg",
    img2: "/images/8.jpg",
    img3: "/images/9.jpg",
    postId: 9,
    recoverystate: 0
  },
  {
    imagesrc: "/images/8.jpg",
    name: "电脑",
    lackofitems: "cpu、硬盘、电源",
    price: "99",
    starttime: "2017-04-13",
    endtime: "2018-11-14",
    numbers: "9",
    recoverynumber: "11110",
    recoveryvariety: "设备",
    recoverymode: "上门回收",
    img1: "/images/1.jpg",
    img2: "/images/8.jpg",
    img3: "/images/9.jpg",
    postId: 10,
    recoverystate: 0
  },
  {
    imagesrc: "/images/8.jpg",
    name: "电脑",
    lackofitems: "cpu、硬盘、电源",
    price: "99",
    starttime: "2017-04-13",
    endtime: "2018-11-14",
    numbers: "9",
    recoverynumber: "11110",
    recoveryvariety: "设备",
    recoverymode: "上门回收",
    img1: "/images/1.jpg",
    img2: "/images/8.jpg",
    img3: "/images/9.jpg",
    postId: 11,
    recoverystate: 2
  },
  {
    imagesrc: "/images/8.jpg",
    name: "电脑",
    lackofitems: "cpu、硬盘、电源",
    price: "99",
    starttime: "2017-04-13",
    endtime: "2018-11-14",
    numbers: "9",
    recoverynumber: "11110",
    recoveryvariety: "设备",
    recoverymode: "上门回收",
    img1: "/images/1.jpg",
    img2: "/images/8.jpg",
    img3: "/images/9.jpg",
    postId: 12,
    recoverystate: 2
  },
]

module.exports = {
  local: local_database
}